### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by anakimluke** [Saruspete/lolcat#2]
Hi!

Are you the original author of the code? If so, would you consider adding a license to the repository?

I was reluctant to ask because of how short the script is.

btw I like how elegant this implementation is, even though I don't know awk 😅

Thanks!

**Comment by Saruspete** [comment]
Hello !

Good catch, let's go with MIT license. As you said, it's very trivial script :smile: 
And thanks to joknarf for the cleanup (he really taught me awk)

fwiw, I guess pretty much every rainbow-related tool is somewhat based on the algorithms on this page: https://krazydad.com/tutorials/makecolors.php

Is it ok for you ?

**Comment by anakimluke** [comment]
Yep, sounds good. Thanks for the link! It's very extensive! It'll surely be useful if I'm to make my own implementation ;)
